package io.github.projectmapk.sealedClassEnumizer.compiler.testing

// 診断 ID → CLI 出力メッセージ断片の対応表（docs/コンパイラプラグイン設計01.md §7.2・§7.3。
// 文言の正は EnumizeErrorMessages.kt）。
//
// K2 CLI は診断 ID（ファクトリ名）を出力しないため、各診断を一意に識別できるメッセージ断片で照合する。
// パラメータ付き診断（factory1/2）は MessageFormat 処理で引用符が変化する（'@Enumize'→@Enumize・
// ''{0}''→'値'）ため、引用符に隣接しない断片を選ぶ（パラメータ無しの factory0 は原文どおり出力される）。
object DiagFragments {
    // ---- プラグイン診断（ENUMIZE_*） ----
    const val NOT_SEALED = "is applicable only to a sealed class or a sealed interface"
    const val MULTIPLE_HIERARCHIES = "belongs to more than one"
    const val NESTED_IN_HIERARCHY = "cannot be applied to a member of the"
    const val AMBIGUOUS_KIND = "The kind of this type is ambiguous"
    const val INNER_LEAF = "cannot be an inner class because an inner class"
    const val KIND_TYPE_NOT_DENOTABLE = "cannot be denoted for leaf"
    const val COMPANION_LEAF_CONFLICT = "cannot itself be a leaf of any"
    const val LABEL_CLASH = "Duplicated label"
    // INVALID_LABEL は factory1 のパラメータへ理由文を渡す形式のため、理由文の断片で照合する
    const val INVALID_LABEL_TARGET = "applicable only to a leaf declaration of an"
    const val INVALID_LABEL_BLANK = "must not be blank"
    const val MEMBER_CONFLICT = "conflicts with a declaration generated by"
    const val MANUAL_IMPL_OUTSIDE_HIERARCHY = "from outside its hierarchy"
    const val MANUAL_SUPERTYPE_MISMATCH = "does not match the generated supertype"
    const val RESERVED_NAME_CLASH = "already declares a nested classifier named"
    const val EXTENSION_SHADOWED = "extension property at call sites"

    // ---- 言語（コンパイラ本体）診断: プラグイン診断との切り分け・合流確認に使う実測断片 ----
    const val LANG_WRONG_ANNOTATION_TARGET = "not applicable to target"
    const val LANG_SEALED_FUN_INTERFACE = "'sealed fun interface' is unsupported"
    const val LANG_EXPOSED_SUPER_CLASS = "subclass exposes its"
    const val LANG_ABSTRACT_MEMBER_NOT_IMPLEMENTED = "does not implement abstract"
    const val LANG_WHEN_NOT_EXHAUSTIVE = "must be exhaustive"
    const val LANG_SUPERTYPE_APPEARS_TWICE = "supertype appears twice"
    const val LANG_PLATFORM_DECLARATION_CLASH = "Inherited platform declarations clash"
    const val LANG_PROJECTION_IN_ARGUMENT = "Projection"
    const val LANG_UPPER_BOUND_VIOLATED = "bound"
    const val LANG_CANNOT_WEAKEN_ACCESS = "weaken"
    const val LANG_EXPOSED_RETURN_TYPE = "exposes"
}
