package io.github.projectmapk.gradle

// 診断 ID → CLI 出力メッセージ断片の対応表（docs/コンパイラプラグイン設計01.md §7.2・§7.3。
// 文言の正は compiler-plugin の EnumizeErrorMessages.kt）。
//
// K2 CLI は診断 ID（ファクトリ名）を出力しないため、各診断を一意に識別できるメッセージ断片で照合する。
// パラメータ付き診断（factory1/2）は MessageFormat 処理で引用符が変化する（'@Enumize'→@Enumize・
// ''{0}''→'値'）ため、引用符に隣接しない断片を選ぶ（パラメータ無しの factory0 は原文どおり出力される）。
object DiagFragments {
    // ---- プラグイン診断（ENUMIZE_*） ----
    const val NOT_SEALED = "is applicable only to a sealed class or a sealed interface"
    const val ALIASED_ANNOTATION = "applied through a typealias or an import alias"
    const val ON_EXPECT = "cannot be applied to an expect declaration"
    const val ON_ACTUAL = "cannot be applied to an actual declaration"
    const val MULTIPLE_HIERARCHIES = "belongs to more than one"
    const val NESTED_IN_HIERARCHY = "cannot be applied to a member of the"
    const val AMBIGUOUS_KIND = "The kind of this type is ambiguous"
    const val INNER_LEAF = "cannot be an inner class because an inner class"
    const val LABEL_CLASH = "Duplicated label"
    const val MEMBER_CONFLICT = "conflicts with a declaration generated by"
    const val MANUAL_IMPL_OUTSIDE_HIERARCHY = "from outside its hierarchy"

    // ---- 言語（コンパイラ本体）診断: プラグイン診断との切り分け・合流確認に使う実測断片 ----
    const val LANG_CONFLICTING_DECLARATIONS = "Conflicting declarations:"
    const val LANG_MANY_IMPL_MEMBER = "because it inherits multiple interface methods"
    const val LANG_INCONSISTENT_TYPE_ARGS = "has inconsistent values"
    const val LANG_WHEN_NOT_EXHAUSTIVE = "must be exhaustive"
    const val LANG_SEALED_DIFFERENT_MODULE = "different module"
}
