package org.wrongwrong.sealedClassEnumizer.compiler.fir.checkers

import org.jetbrains.kotlin.diagnostics.KtDiagnosticFactoryToRendererMap
import org.jetbrains.kotlin.diagnostics.rendering.BaseDiagnosticRendererFactory
import org.jetbrains.kotlin.diagnostics.rendering.CommonRenderers

// メッセージは英語（診断 ID とパラメータで機械可読性を確保）とし、「どうすれば直るか」を含める（設計01 §7.3）
object EnumizeErrorMessages : BaseDiagnosticRendererFactory() {
    override val MAP by KtDiagnosticFactoryToRendererMap("SealedClassEnumizer") { map ->
        map.put(
            EnumizeErrors.ENUMIZE_NOT_SEALED,
            "'@Enumize' is applicable only to a sealed class or a sealed interface. " +
                "Make the declaration sealed or remove the annotation.",
        )
        map.put(
            EnumizeErrors.ENUMIZE_ON_EXPECT,
            "'@Enumize' cannot be applied to an expect declaration: the hierarchy may differ per actual. " +
                "Apply '@Enumize' to a non-expect sealed declaration instead.",
        )
        map.put(
            EnumizeErrors.ENUMIZE_ON_ACTUAL,
            "'@Enumize' cannot be applied to an actual declaration in this version. " +
                "Apply '@Enumize' to a non-actual sealed declaration instead.",
        )
        map.put(
            EnumizeErrors.ENUMIZE_MULTIPLE_FAMILIES,
            "This declaration belongs to more than one '@Enumize' hierarchy ({0} and {1}). " +
                "Keep the declaration in a single '@Enumize' hierarchy.",
            CommonRenderers.STRING,
            CommonRenderers.STRING,
        )
        map.put(
            EnumizeErrors.ENUMIZE_NESTED_IN_HIERARCHY,
            "'@Enumize' cannot be applied to a member of the '@Enumize' hierarchy of ''{0}''. " +
                "Remove the annotation from this declaration.",
            CommonRenderers.STRING,
        )
        map.put(
            EnumizeErrors.ENUMIZE_AMBIGUOUS_KIND,
            "The kind of this type is ambiguous: it is a subtype of multiple leaves ({0} and {1}) " +
                "of the same '@Enumize' hierarchy. Make it a subtype of exactly one leaf.",
            CommonRenderers.STRING,
            CommonRenderers.STRING,
        )
        map.put(
            EnumizeErrors.ENUMIZE_INNER_LEAF,
            "A leaf of an '@Enumize' hierarchy cannot be an inner class because an inner class " +
                "cannot have a companion object. Remove the 'inner' modifier or the hierarchy membership.",
        )
        map.put(
            EnumizeErrors.ENUMIZE_KIND_NOT_ACCESSIBLE,
            "The kind of this leaf ({0}) is not accessible from the body scope of the '@Enumize' base, " +
                "so entries cannot be built. Widen its visibility or move the leaf into the base declaration.",
            CommonRenderers.STRING,
        )
        map.put(
            EnumizeErrors.ENUMIZE_KIND_TYPE_NOT_DENOTABLE,
            "The return type of 'asEnumish' cannot be denoted for leaf ''{0}'': the leaf is more visible " +
                "than both its companion and the generated Enumish. Make the companion at least as visible " +
                "as the leaf, or narrow the leaf visibility to the base or below.",
            CommonRenderers.STRING,
        )
        map.put(
            EnumizeErrors.ENUMIZE_COMPANION_LEAF_CONFLICT,
            "The companion object of a leaf class cannot itself be a leaf of the same '@Enumize' hierarchy " +
                "(the kind would correspond to two leaves). Remove the hierarchy supertype from the companion.",
        )
        map.put(
            EnumizeErrors.ENUMIZE_LABEL_CLASH,
            "Duplicated label ''{0}'' in the '@Enumize' hierarchy (also used by {1}). " +
                "Rename one of the leaves so that all labels are unique.",
            CommonRenderers.STRING,
            CommonRenderers.STRING,
        )
        map.put(
            EnumizeErrors.ENUMIZE_MANUAL_MEMBER_CONFLICT,
            "Member ''{0}'' conflicts with a declaration generated by '@Enumize'. " +
                "Remove or rename the manual member.",
            CommonRenderers.STRING,
        )
        map.put(
            EnumizeErrors.ENUMIZE_MANUAL_IMPL_OUTSIDE_HIERARCHY,
            "This declaration implements the generated Enumish of ''{0}'' from outside its hierarchy. " +
                "The sealed inheritors list cannot include such an implementation, so it would be rejected " +
                "at runtime. Make the declaration a member of the hierarchy of ''{0}'' or remove the supertype.",
            CommonRenderers.STRING,
        )
        map.put(
            EnumizeErrors.ENUMIZE_MANUAL_SUPERTYPE_MISMATCH,
            "Manually declared supertype ''{0}'' does not match the generated supertype ''{1}''. " +
                "Use the same type argument as the generated declaration or remove the manual supertype.",
            CommonRenderers.STRING,
            CommonRenderers.STRING,
        )
        map.put(
            EnumizeErrors.ENUMIZE_RESERVED_NAME_CLASH,
            "The '@Enumize' target already declares a nested classifier named 'Enumish', " +
                "which clashes with the generated declaration. Rename the existing nested declaration.",
        )
        map.put(
            EnumizeErrors.ENUMIZE_COMPANION_REQUIRED,
            "This leaf class needs a companion object to host its kind, and automatic generation " +
                "did not apply here. Declare 'companion object' explicitly.",
        )
        map.put(
            EnumizeErrors.ENUMIZE_CROSS_SOURCE_SET,
            "Inheritor ''{0}'' of the '@Enumize' hierarchy is declared in a different source set. " +
                "A sealed hierarchy must be contained in a single source set; move the inheritor.",
            CommonRenderers.STRING,
        )
        map.put(
            EnumizeErrors.ENUMIZE_EXTENSION_SHADOWED,
            "This member named 'label' shadows the 'Enumized.label' extension property at call sites. " +
                "Use 'asEnumish().label' to reliably read the kind label.",
        )
        map.put(
            EnumizeErrors.ENUMIZE_ENUM_LEAF_UNSUPPORTED,
            "An enum class leaf is not supported in this configuration. " +
                "Replace the enum class leaf with object or class leaves.",
        )
    }
}
