package org.wrongwrong.fixtures.internalleaves

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertSame

// public 基底 + internal 末端（全種別）のモジュール内 box テスト
// （docs/テストケース管理.md TC-GAP-015 生成側 / TC-VIS-010 / TC-VIS-018 / TC-VIS-023 / TC-VIS-026 /
//  TC-VIS-034 / TC-VIS-039 / TC-VIS-044）
class InternalLeavesTest {
    // TC-VIS-010 / TC-VIS-034 / TC-VIS-044: 別ファイルの internal トップレベル末端は同モジュールから参照可能で
    // アクセサ不要（直接参照。コンパイル成立が証明）、可視性の低い kind も entries に通常どおり載る
    @Test
    fun internalLeavesOfAllShapesAppearInEntries() {
        assertEquals(
            listOf("AutoLeaf", "ClsLeaf", "EnLeaf", "ObLeaf", "PubOb", "VvLeaf"),
            InternalLeaves.Enumish.entries.map { it.label },
        )
    }

    // TC-VIS-023: 明示 internal companion → eff(C) = eff(L) = internal で規則 1（具体型で受けられる）
    @Test
    fun explicitInternalCompanionUsesConcreteType() {
        val kind: ClsLeaf.Companion = ClsLeaf(1).asEnumish()
        assertSame(ClsLeaf.Companion, kind)
    }

    // TC-VIS-026: 自動生成 companion は宣言 public・実効 internal = 末端 → 常に規則 1（具体型）
    @Test
    fun autoGeneratedCompanionUsesConcreteType() {
        val kind: AutoLeaf.Companion = AutoLeaf(1).asEnumish()
        assertSame(AutoLeaf.Companion, kind)
    }

    // TC-GAP-015: internal enum 末端は label = クラス名 / name = 定数名の管轄分離のまま動作する
    @Test
    fun internalEnumLeafKeepsNameAndLabelSeparation() {
        assertEquals(listOf("A", "EnLeaf"), listOf(EnLeaf.A.name, EnLeaf.A.asEnumish().label))
        assertSame(EnLeaf.Companion, InternalLeaves.Enumish.valueOf("EnLeaf"))
    }

    // TC-VIS-018 / TC-GAP-015: internal value class 末端の boxing でも kind は同一シングルトン
    @Test
    fun internalValueClassLeafKeepsKindIdentityAcrossBoxing() {
        val boxed: InternalLeaves = VvLeaf(1)
        assertSame(VvLeaf(2).asEnumish(), boxed.asEnumish())
        assertSame(VvLeaf.Companion, boxed.asEnumish())
    }

    // TC-VIS-039: internal 末端を含む階層でも、モジュール内（全 kind 可視）の kind-when は else 不要
    @Test
    fun kindWhenIsExhaustiveInsideModule() {
        val branches = InternalLeaves.Enumish.entries.map { kind ->
            when (kind) {
                AutoLeaf.Companion -> "auto"
                ClsLeaf.Companion -> "cls"
                EnLeaf.Companion -> "enum"
                ObLeaf -> "ob"
                PubOb -> "pub"
                VvLeaf.Companion -> "value"
            }
        }
        assertEquals(listOf("auto", "cls", "enum", "ob", "pub", "value"), branches)
    }
}
