package org.wrongwrong.fixtures.openleaf

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertSame
import org.wrongwrong.sealedClassEnumizer.label

// open class 末端（V10）と実装者ゼロ interface 末端の box テスト
// （docs/テストケース管理.md TC-LEAF-007 / TC-LEAF-035 / TC-LEAF-084 / TC-LEAF-095 / TC-BOX-076 / TC-BOX-077
// / TC-BOX-082）
class FigureTest {
    // TC-LEAF-007 / TC-LEAF-084: open class 末端 + companion 自動生成。kind = Round.Companion
    @Test
    fun openClassLeafHasAutoGeneratedCompanionKind() {
        assertSame(Figure.Round.Companion, Figure.Round(1).asEnumish())
        assertEquals("Round", Figure.Round.Companion.label)
        assertEquals(Figure.Round::class, Figure.Round.Companion.enumizedClass)
    }

    // TC-BOX-082: open 末端は自身もインスタンス化でき、その値も同じ kind に分類される
    @Test
    fun openLeafItselfAndSubclassShareKind() {
        val self: Figure = Figure.Round(9)
        val sub: Figure = Oval()
        assertSame(self.asEnumish(), sub.asEnumish())
    }

    // TC-LEAF-035: open class 末端のサブタイプ（同一モジュール）は Round の kind に吸収される
    @Test
    fun subclassOfOpenLeafIsAbsorbed() {
        val oval: Figure = Oval()
        assertSame(Figure.Round.Companion, oval.asEnumish())
        assertEquals("Round", oval.label)
    }

    // TC-LEAF-095: 末端のサブタイプである object は自身の kind を作らず吸収される
    @Test
    fun objectSubtypeOfLeafIsAbsorbedNotAKind() {
        assertSame(Figure.Round.Companion, SpecialRound.asEnumish())
        assertEquals("Round", SpecialRound.label)
    }

    // TC-BOX-076: 多段サブタイプ（Square : Quad : Round）でも最上位の末端の kind に吸収される
    @Test
    fun multiLevelSubtypeIsAbsorbedIntoLeafKind() {
        val square: Figure = Square()
        assertSame(Figure.Round.Companion, square.asEnumish())
        assertEquals(
            listOf("Round", Figure.Round::class),
            listOf(square.label, square.asEnumish().enumizedClass),
        )
    }

    // TC-BOX-077: 実装者ゼロの interface 末端でも kind は entries に載り valueOf で解決できる
    @Test
    fun interfaceLeafWithoutImplementorsStillHasKind() {
        assertEquals(listOf("Ghost", "Round"), Figure.Enumish.entries.map { it.label })
        assertSame(Figure.Ghost.Companion, Figure.Enumish.valueOf("Ghost"))
        assertEquals(Figure.Ghost::class, Figure.Ghost.Companion.enumizedClass)
    }
}
